# docker compose build --no-cache --progress plain
version: "3.7"

services:
  app:
    container_name: bolitoday
    volumes:
      - ./database/:/app/database/

    build:
      context: .

    env_file:
      - ./.env

